### ISSUE TITLE
setup local mathoid instance on test server to make test faster and independent from the remote server.

### ISSUE THREAD

**Issue by leokraemer** [ag-gipp/mathosphere#108]
Some test require mathoid and use an instance that is hosted somewhere. This is bad for Travis automated tests, since they might fail when this is unreachable.
Therefore maven tests should setup a local mathoid instance.

Good candidate for the implementation: https://github.com/eirslett/frontend-maven-plugin

**Comment by physikerwelt** [comment]
@vstange @AndreG-P I think https://github.com/eirslett/frontend-maven-plugin is a good alternative to our current travis hacks. What do you think?

https://github.com/ag-gipp/mathosphere/blob/7fdbfe6cc89d8895b411bfdeeabca12f8d3fa92c/.travis.yml#L20-L24
